Fix issues in working with NVM in script

diff --git a/serviceWrappers/linux/kLiveController b/serviceWrappers/linux/kLiveController
--- a/serviceWrappers/linux/kLiveController
+++ b/serviceWrappers/linux/kLiveController
@@ -23,7 +23,7 @@ KLIVE_CONTROLLER_PREFIX="/opt/kaltura/liveController/latest"
 NODE_PATH="$KLIVE_CONTROLLER_PREFIX/node_modules"
 FOREVER="$NODE_PATH/forever/bin/forever"
 APPLICATION_PATH="$KLIVE_CONTROLLER_PREFIX/lib/App.js"
-LOG_DIR="/var/log"
+LOG_DIR="/var/log/${NAME}"
 PID_DIR="/var/run"
 MIN_UPTIME="5000"
 SPIN_SLEEP_TIME="2000"
@@ -31,7 +31,13 @@ export PATH=$PATH:$NODE_PATH/forever/bin:/usr/local/bin
 
 loadNvm() {
     # This loads nvm
-    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || (echo "nvm not found in $NVM_DIR, this is a must, Exiting!" ; exit 1 )
+    [ -z "$NVM_DIR" ] && NVM_DIR="$HOME/.nvm"
+    if [ -s "$NVM_DIR/nvm.sh" ] ; then
+        source "$NVM_DIR/nvm.sh"
+    else
+        echo "nvm not found in $NVM_DIR, this is a must, Exiting!"
+        exit 1
+    fi
 }
 
 start() {
