changes based on comments from Jess after testing (#481)

diff --git a/serviceWrappers/linux/kLiveController b/serviceWrappers/linux/kLiveController
--- a/serviceWrappers/linux/kLiveController
+++ b/serviceWrappers/linux/kLiveController
@@ -37,19 +37,22 @@ HOME=${HOME:-~}
 
 loadNvm() {
     # This loads nvm
+    # must cd/pushd due to a bug in /root/.nvm/nvm.sh call to nvm_find_nvmrc()  
+    pushd ${KLIVE_CONTROLLER_PREFIX}
     [ -z "${NVM_DIR}" ] && NVM_DIR="${HOME}/.nvm"
-    if [ -s "${NVM_DIR}/nvm.sh" ] ; then
+    if [ -s "${NVM_DIR}/nvm.sh" ]; then
         source "${NVM_DIR}/nvm.sh"
-        if [ -s ${KLIVE_CONTROLLER_PREFIX}/.nvmrc ] ; then
+        if [ -s ".nvmrc" ] ; then
             nvm use || nvm install
         else
-            echo "no .nvmrc in ${PWD} , Exiting"
+            echo "no .nvmrc in ${KLIVE_CONTROLLER_PREFIX}, Exiting"
             exit 1
         fi
     else
         echo "nvm not found in ${NVM_DIR}, this is a must, Exiting!"
         exit 1
     fi
+    popd
 }
 
 start() {
@@ -82,16 +85,18 @@ stop() {
     for prefix in 0 1 ; do
         PIDFILE="$PID_DIR/${NAME}_${prefix}.pid"
         if [ -f $PIDFILE ]; then
+            local pid=$( cat ${PIDFILE} )
             echo "Shutting down ${NAME}_${prefix}"
             # Tell Forever to stop the process.
-            ${FOREVER} stop $( cat ${PIDFILE} )
-            if [ $? -ne 0 ]; then
+            ${FOREVER} stop ${pid}
+            status -p ${PIDFILE}
+            if [ $? -eq 0 ]; then
                RETVAL=$(( ${RETVAL} + $? ))
-               echo "failed to stop ${NAME}_${prefix} with error $?"
+               echo "failed to stop ${NAME}_${prefix}, ${pid}"
                killApp
-               # return $? or RETVAL?
-               #return ${RETVAL}
+               return ${RETVAL}
             else
+               echo "${NAME}_${prefix}, ${pid}, successfully stopped"
                rm -f $PIDFILE
             fi
         else
