some cosmetic updates

diff --git a/liveRecorder/serviceWrappers/linux/liveRecorder b/liveRecorder/serviceWrappers/linux/liveRecorder
--- a/liveRecorder/serviceWrappers/linux/liveRecorder
+++ b/liveRecorder/serviceWrappers/linux/liveRecorder
@@ -30,15 +30,15 @@ NAME=${APP_NAME}
 APPLICATION_PATH=${APPDIR}/main.py
 LOG_DIR="/var/log/${APP_NAME}"
 PID_DIR="/var/run"
-PIDFILE="$PID_DIR/${NAME}.pid"
-LOGFILE="$LOG_DIR/${NAME}-service.log"
+PIDFILE="${PID_DIR}/${NAME}.pid"
+LOGFILE="${LOG_DIR}/${NAME}-service.log"
 
 RETVAL=0
 
 createFolders() {
 	[ -d ${LOG_DIR} ] || mkdir -p ${LOG_DIR}
 	SHARED_APP_DIR=$(python ${SCRIPT_DIR}/getRecordingBaseDir.py)
-	echo "Creating folders in ${SHARED_APP_DIR} for $HOSTNAME"
+	echo "Creating folders in ${SHARED_APP_DIR} for ${HOSTNAME}"
 	if [ -d  ${SHARED_APP_DIR} ] ; then 
 		mkdir -p ${SHARED_APP_DIR}/${HOSTNAME}/{UploadTask/{incoming,failed,processing},ConcatenationTask/{failed,processing}}
 		[ -L ${SHARED_APP_DIR}/${HOSTNAME}/ConcatenationTask/incoming ] || ln -s ${SHARED_APP_DIR}/incoming ${SHARED_APP_DIR}/${HOSTNAME}/ConcatenationTask/incoming
@@ -50,31 +50,33 @@ createFolders() {
 
 start() {
 	createFolders || exit 1
-    if [ -f $PIDFILE ]; then
+    if [ -f ${PIDFILE} ]; then
         echo "${NAME} already running"
     else
         echo "Starting ${NAME}"
-        python2.7 $APPLICATION_PATH >> $LOGFILE  2>&1 &
+        python2.7 ${APPLICATION_PATH} >> ${LOGFILE}  2>&1 &
 	    RETVAL=$?
-        echo $! > $PIDFILE
-        if [ $RETVAL -eq 0 ] ; then 
-			echo "started ${NAME} with pid $(cat $PIDFILE)"
+        echo $! > ${PIDFILE}
+        if [ ${RETVAL} -eq 0 ] ; then
+			echo "started ${NAME} with pid $(cat ${PIDFILE})"
 		else
-			echo "starting ${NAME} failed. please see $LOGFILE "
+			echo "starting ${NAME} failed. please see ${LOGFILE}"
 		fi
 	fi
 }
 
 stop() {
-    if [ -f $PIDFILE ]; then
+    if [ -f ${PIDFILE} ]; then
         echo "Shutting down ${NAME}"
-        kill $( cat $PIDFILE ) >> $LOGFILE
-        my_status
-        if [ ${RETVAL} -ne 0 ]; then
-            killAll
+        kill $( cat ${PIDFILE} ) >> ${LOGFILE}
+        if [ $? -ne 0 ]; then
+            killApp
+            RETVAL=$?
+        else
+            rm -f ${PIDFILE}
         fi
     else
-        echo "${NAME} is not running."
+        echo "${NAME} is not running"
     fi
 }
 
@@ -93,7 +95,7 @@ my_status() {
 
 killApp() {
     echo "Aggressively kill all Live processes"
-    pkill -f $APPLICATION_PATH 
+    pkill -f ${APPLICATION_PATH}
     echo "Removing PID file"
     rm -f ${PIDFILE}
 }
@@ -116,4 +118,4 @@ case "$1" in
         exit 1
         ;;
 esac
-exit $RETVAL
+exit ${RETVAL}
diff --git a/serviceWrappers/linux/kLiveController b/serviceWrappers/linux/kLiveController
--- a/serviceWrappers/linux/kLiveController
+++ b/serviceWrappers/linux/kLiveController
@@ -37,18 +37,18 @@ HOME=${HOME:-~}
 
 loadNvm() {
     # This loads nvm
-    cd $KLIVE_CONTROLLER_PREFIX
-    [ -z "$NVM_DIR" ] && NVM_DIR="$HOME/.nvm"
-    if [ -s "$NVM_DIR/nvm.sh" ] ; then
-        source "$NVM_DIR/nvm.sh"
+    cd ${KLIVE_CONTROLLER_PREFIX}
+    [ -z "${NVM_DIR}" ] && NVM_DIR="${HOME}/.nvm"
+    if [ -s "${NVM_DIR}/nvm.sh" ] ; then
+        source "${NVM_DIR}/nvm.sh"
         if [ -s .nvmrc ] ; then
             nvm use || nvm install
         else
-            echo "no .nvmrc in $PWD , Exiting"
+            echo "no .nvmrc in ${PWD} , Exiting"
             exit 1
         fi
     else
-        echo "nvm not found in $NVM_DIR, this is a must, Exiting!"
+        echo "nvm not found in ${NVM_DIR}, this is a must, Exiting!"
         exit 1
     fi
 }
@@ -58,20 +58,20 @@ start() {
     loadNvm
     RETVAL=0
     for prefix in 0 1 ; do
-        PIDFILE="$PID_DIR/${NAME}_${prefix}.pid"
-        LOGFILE="$LOG_DIR/${NAME}_${prefix}-forever.log"
-        if [ -f $PIDFILE ]; then
+        PIDFILE="${PID_DIR}/${NAME}_${prefix}.pid"
+        LOGFILE="${LOG_DIR}/${NAME}_${prefix}-forever.log"
+        if [ -f ${PIDFILE} ]; then
             echo "${NAME}_${prefix} already running"
         else
             echo "Starting ${NAME}_${prefix}"
-            $FOREVER \
-              --pidFile $PIDFILE \
+            ${FOREVER} \
+              --pidFile ${PIDFILE} \
               -a \
-              -l $LOGFILE \
-              --minUptime $MIN_UPTIME \
-              --spinSleepTime $SPIN_SLEEP_TIME \
-              start $APPLICATION_PATH prefix:${prefix}
-	        RETVAL=$(( $RETVAL + $? ))
+              -l ${LOGFILE} \
+              --minUptime ${MIN_UPTIME} \
+              --spinSleepTime ${SPIN_SLEEP_TIME} \
+              start ${APPLICATION_PATH} prefix:${prefix}
+	        RETVAL=$(( ${RETVAL} + $? ))
         fi
     done
 }
@@ -82,17 +82,20 @@ stop() {
     for prefix in 0 1 ; do
         PIDFILE="$PID_DIR/${NAME}_${prefix}.pid"
         if [ -f $PIDFILE ]; then
-            echo "Shutting down ${NAME}_${prefix}"
-            # Tell Forever to stop the process.
-            $FOREVER stop $( cat $PIDFILE )
-	        RETVAL=$(( $RETVAL + $? ))
-            status -p ${PIDFILE}
-            ${RETVAL}=$?
-	        if [ ${RETVAL} -ne 0 ]; then
-                  killApp()
+	        echo "Shutting down ${NAME}_${prefix}"
+	        # Tell Forever to stop the process.
+	        ${FOREVER} stop $( cat ${PIDFILE} )
+	        if [ $? -ne 0 ]; then
+	            RETVAL=$(( ${RETVAL} + $? ))
+	            echo "failed to stop ${NAME}_${prefix} with error $?"
+	            killApp
+	            # return $? or RETVAL?
+	            #return ${RETVAL}
+	        else
+	           rm -f $PIDFILE
 	        fi
-        else
-            echo "${NAME}_${prefix} is not running."
+	    else
+            echo "${NAME}_${prefix} is not running"
         fi
     done
 }
@@ -108,19 +111,22 @@ restart() {
 my_status() {
     RETVAL=0
     for prefix in 0 1 ; do
-        PIDFILE="$PID_DIR/${NAME}_${prefix}.pid"
-        if [ -f $PIDFILE ]; then
+        PIDFILE="${PID_DIR}/${NAME}_${prefix}.pid"
+        if [ -r ${PIDFILE} ]; then
             status -p ${PIDFILE}
-            ${RETVAL}=$?
-        if [ ${RETVAL} -ne 0 ]; then
-            return ${RETVAL}
+	        if [ $? -ne 0 ]; then
+	            RETVAL=$?
+	            return ${RETVAL}
+	        fi
+	    else
+	        echo "${PIDFILE} is empty, ${NAME} is not running (verify by: ps aux | grep node)"
         fi
     done
 }
 
 killApp() {
-    echo "Aggressively kill all Live processes"
-    pkill -f $APPLICATION_PATH 
+    echo "Aggressively kill all ${NAME} processes"
+    pkill -f ${APPLICATION_PATH}
     echo "Remove all PID files"
     rm -f ${PID_DIR}/${NAME}*.pid
 }
@@ -143,4 +149,4 @@ case "$1" in
         exit 1
         ;;
 esac
-exit $RETVAL
+exit ${RETVAL}
